export const ADD_PRODUCT = "product/addProduct"
export const ADD_CART = "product/addCart"
export const REMOVE_ITEM = "product/removeItem"
export const INCREMENT_PRODUCT = "product/incrementProductQuantity"
export const DECREMENT_PRODUCT = "product/decrementProductQuantity"